# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def fibonacci(n)
  return 1 if n < 2 
  fibonacci(n - 1) + fibonacci(n - 2)
end

n = 0
sum = 0

while fibonacci(n) < 4000000 do
  sum += fibonacci(n) if fibonacci(n) % 2 == 0    
  n += 1
end

puts sum